### PR TITLE
Item table and relationships

### LINKED ISSUE #16: Items Table and relationships
Items have many characters, characters have many items.

Items should have a name
and description

### PR DESCRIPTION
**Pull request by DanielEFrampton**
Resolves #16 

Take two, rebased and updated schema file to get Mike's GameSession changes in.

Creates Item model and ItemCharacter join table & model, updated Character with relationship to Item through ItemCharacter, etc., etc. Can't believe I got snookered into making the many-to-many.

State of tests:
```
........................................

Finished in 0.9328 seconds (files took 5.03 seconds to load)
40 examples, 0 failures

Coverage report generated for RSpec to /Users/dframpton/code/projects/cobalt_reserve/coverage. 411 / 411 LOC (100.0%) covered.
```

you found a mystical pizza

### CODE REVIEW

**Comment by mikedao** [comment]
Wait, why did you make it a many to many?

**Comment by DanielEFrampton** [comment]
> Wait, why did you make it a many to many?

Lol. I think I read the user story too quickly, which says "Items have many characters, characters have many items." In retrospect obviously an item would only belong to one character at a time. I'll change it to characters have many items, and an individual item belongs to a character.

**Comment by mikedao** [comment]
I mean I'm okay with going with this if you are?

**Comment by DanielEFrampton** [comment]
I don't see a good reason to stick with it unless we want to track the ownership of an item across multiple characters for some reason. It'd be a fun data point maybe.

**Comment by mikedao** [comment]
yeah merging it in, you already did it, and it helps with our long term goal of doing some fun analytics

**Comment by iandouglas** [comment]
One idea here would be to have an Items table and an ItemsInstance table that was then a many to many to a user. The main Items table could have primary stats like weight, and how many could exist in the world at a time. The ItemInstance, then, could be one of those Items which is then tracked to a single character.

**Comment by DanielEFrampton** [comment]
I like that @iandouglas. Some of that could happen on the item_character join table; it occurred to me that it's a good place for a "quantity" field. Under the hood of D&D, does this map to how items are handled? Is there one base item template that other items are instances/variations of?

**Comment by iandouglas** [comment]
It would allow us to have just a "short sword" in the Items table and a "+1 short sword" in the items instance table, for example. I agree that tracking some of that in the join table would be okay but would we really want a full copy of all stats in there every time we made a new item, or just a reference back to the main stats plus some other field to track modifiers?

**Comment by mikedao** [comment]
I think that in terms of magical items as opposed to normal items having variants should be separate instances. There are too many modifiers and too many special rules to really practically coming up with a general case. The simple thing would be not to store the attributes, and intricacies, but simply link to dndbeyond, who has done all of the heavy lifting for us already

**Comment by iandouglas** [comment]
Good point. Is there a field in our db to store the URL for dndbeyond's page?

**Pull request merged**
