### PR TITLE
Fix edit field pre-population

### LINKED ISSUE #77: Defect: "Edit Character" doesn't auto-populate species and class menus with existing values
"Edit Character" doesn't auto-populate species and class menus with existing values.

Profile:
Screen Shot 2020-07-30 at 1 01 32 PM

Edit screen after clicking "Edit Character":
Screen Shot 2020-07-30 at 1 01 40 PM

### PR DESCRIPTION
**Pull request by DanielEFrampton**
Resolves #77

- Fixes Character Edit view so that "Species" and "Class" fields are pre-populated with existing character info
- Fixes select field labels so they are associated with select fields for test purposes
- Revises Character factory to pull from actual data now available in `Character.species` and `Character.classes`
- Lowers minimum character length of `species` to 3 in model validation so Orcses and Elves can play

elves kissing orcs

### CODE REVIEW

**Comment by mikedao** [comment]
Gif game real strong.

**Comment by mikedao** [comment]
Taking a step back, do we want to define races here? Was planning on using the alternate race stuff to allow people to build their own half-races?

**Comment by DanielEFrampton** [comment]
> Taking a step back, do we want to define races here? Was planning on using the alternate race stuff to allow people to build their own half-races?

Yeah I think that makes sense. Following up on Discord

**Comment by DanielEFrampton** [comment]
For posterity: I think the character form is a good place to define ancestry per the Ancestry & Culture rules. I'm going to make a new issue for it and merge what we've got here.

**Pull request merged**
